"""Add is_active to Team model

Revision ID: 11e9b76f0dec
Revises: afe48ee5e3f4
Create Date: 2026-01-29 10:22:17.801683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e9b76f0dec'
down_revision: Union[str, Sequence[str], None] = 'afe48ee5e3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'is_active')
    # ### end Alembic commands ###
