"""Reflect ActivityLog model changes

Revision ID: 2f832863e0e8
Revises: 5c48f6e2e4a9
Create Date: 2026-01-29 14:28:38.244155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f832863e0e8'
down_revision: Union[str, Sequence[str], None] = '5c48f6e2e4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_measurement_id', sa.Integer(), nullable=False),
    sa.Column('measurement_type', sa.Enum('seconds', 'repetitions', 'kilograms', 'meters', 'centimeters', name='measurementtype'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_measurement_id'], ['player_measurements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_values_id'), 'measurement_values', ['id'], unique=False)
    op.add_column('player_measurements', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_measurements', 'is_active')
    op.drop_index(op.f('ix_measurement_values_id'), table_name='measurement_values')
    op.drop_table('measurement_values')
    # ### end Alembic commands ###
